# filepath: /Users/jackmunton/source/darts/netlify.toml
[build]
  command = "npm install && npm run build && bash scripts/post-build.sh"
  publish = "dist"
  
[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--production=false"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["firebase-admin"]

# Netlify Functions for server API routes - these handle SSR
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server/:splat"
  status = 200

# Handle SPA routing for client-side routes
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200
